# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100. File automatically generated. See the documentation to update questions/answers/hints programmatically.



In [1]:
#1. Import the numpy package under the name np
import numpy as np

In [2]:
#2. Print the numpy version and the configuration 
np.__version__

'1.20.3'

In [4]:
#3. Create a null vector of size 10
a=np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#4. How to find the memory size of any array
lst = [1,2,3]
np.size(lst)

3

In [11]:
#5. How to get the documentation of the numpy add function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [21]:
#6. Create a null vector of size 10 but the fifth value which is 1
#hint array[4]
a =np.zeros(10)
a[4] =1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [24]:
#7. Create a vector with values ranging from 10 to 49
b=np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [35]:
#8. Reverse a vector (first element becomes last)
c = b[::-1]
c


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [41]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
d =[1,2,0,0,4,0]
np.nonzero(d)

(array([0, 1, 4]),)

In [44]:
#11. Create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
#12. Create a 3x3x3 array with random values
np.random.random([3,3,3])

array([[[0.74837936, 0.72336903, 0.45278213],
        [0.98560369, 0.7464351 , 0.68245056],
        [0.35037643, 0.69718501, 0.14304076]],

       [[0.43064021, 0.34093264, 0.18927354],
        [0.26649677, 0.22253755, 0.89875998],
        [0.57228758, 0.20291082, 0.16052192]],

       [[0.43386439, 0.15390423, 0.04155414],
        [0.13232616, 0.19322451, 0.07731336],
        [0.42271889, 0.11639193, 0.19823317]]])

In [54]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
e=np.random.random([10,10])
print(e)
print(np.min(e))
print(np.max(e))

[[0.2602139  0.23628591 0.42993306 0.44085572 0.51651659 0.47410383
  0.27831485 0.13888329 0.11903889 0.55593999]
 [0.58325636 0.60229829 0.01894296 0.69910169 0.05547869 0.95191133
  0.80401043 0.99902442 0.90904506 0.33966241]
 [0.37214566 0.43592682 0.4848658  0.94031684 0.31864132 0.00483363
  0.49500792 0.75073786 0.77214784 0.90760075]
 [0.59783321 0.42101347 0.50944183 0.36544139 0.2248067  0.33059179
  0.30260123 0.18448072 0.13820285 0.5774431 ]
 [0.99444246 0.01028586 0.4844242  0.90933081 0.46624713 0.27518994
  0.88133492 0.12944457 0.69973188 0.4870694 ]
 [0.09163152 0.69053055 0.65940847 0.20462377 0.99740774 0.69104114
  0.13349171 0.5865914  0.59694541 0.19785506]
 [0.16821252 0.41652456 0.6016235  0.32070837 0.0112179  0.17595374
  0.08837397 0.21650946 0.10550662 0.72034953]
 [0.11112782 0.45013918 0.32180498 0.48241864 0.8735307  0.51961681
  0.26955772 0.0958716  0.28781553 0.59310772]
 [0.6684027  0.17434774 0.14119748 0.76305834 0.28956652 0.82926771
  0.49695674

In [59]:
#14. Create a random vector of size 30 and find the mean value 
f=np.random.random([30])
print(f)
np.mean(f)

[0.49508476 0.13017756 0.1289515  0.91733374 0.93585321 0.42753996
 0.10478201 0.64237511 0.66368842 0.64933805 0.68305263 0.80739199
 0.08269797 0.35603256 0.44330717 0.61511956 0.84416403 0.6761657
 0.09202016 0.2969498  0.78305232 0.46593883 0.47837942 0.39770774
 0.82766606 0.20541106 0.1622001  0.08099225 0.21750364 0.39259082]


0.4667822710948368

In [88]:
#15. Create a 2d array with 1 on the border and 0 inside 
#np.array[1:-1, 1:-1]
g=np.ones((5,5))
g[1:-1, 1:-1]=0
g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [102]:
#16. How to add a border (filled with 0's) around an existing array? 
h=np.ones((5,5))
np.pad(h,(1))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [103]:
#17. What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

#np.nan =Convert a string or number to a floating point number, if possible.

False

In [133]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
i = np.diag([1, 2, 3, 4],k=-1)
i

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [141]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
j = np.zeros((8,8),int)
# odd rows and even columns
j[1::2,::2] = 1
# even rows and odd columns
j[::2,1::2] = 1
print(j)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [158]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
#k = np.arange(0,336).reshape(6,7,8)
np.unravel_index(100,(6,7,8))


(1, 5, 4)