# Table of Content - Customer Service Study

### [Lab case Study](#00)

### [Pipeline df2](#0):
1.  [Aggregate data into one Data Frame using Pandas.](#1)
2. [Standardizing header names](#2)
3. [Deleting and rearranging columns](#3)
4. [Working with data types – Check the data types of all the columns](#4)
5. [Filtering data and Correcting typos](#5)
6. [Removing duplicates](#6)
7. [Optional:Replacing null values](#7)
8. [Bucketing the data](#8)
9. [Standardizing the data](#9)
10. [Which columns are numerical?](#10)
11. [Which columns are categorical?](#11)
12. [Check and deal with NaN values](#12)


### [Pipeline df3](#15)
1. [Datetime format ](#13)
2. [BONUS: Put all the previously mentioned data transformations into a function/functions.](#14)
3. [Show a plot of the total number of responses.](#16)
4. [Show a plot of the response rate by the sales channel.](#17)
5. [Show a plot of the response rate by the total claim amount.](#18)
6. [Show a plot of the response rate by income.](#19)
7. [Don't Limit your creativity!](#20)
8. [Plot the Correlation Heatmap.](#21)
9. [Clean your notebook ](#22)




# Lab Case Study <a class="anchor" id="00"></a>

### Scenario

You are working as an analyst for an auto insurance company. The company has collected some data about its customers including their demographics, education, employment, policy details, vehicle information on which insurance policy is, and claim amounts. You will help the senior management with some business questions that will help them to better understand their customers, improve their services, and improve profitability.

### Business Objectives

- Retain customers,
- analyze relevant customer data,
- develop focused customer retention programs.

Based on the analysis, take targeted actions to increase profitable customer response, retention, and growth.

### Activities

Refer to the `Activities.md` file where you will find guidelines for some of the activities that you want to do.

### Data

The csv files is provided in the folder. The columns in the file are self-explanatory.

----

# Pipeline  df 2 <a class="anchor" id="0"></a>
cleaning and analysing file1.csv and file2.csv

In [1]:
# import libraries to use (pandas, numpy, matplotlib.pyplot and seaborn)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 

def load_data(path):
    return pd.read_csv(path)

def concat(df2):
    df2=pd.concat([df,df1], ignore_index='TRUE')
        
df = load_data(path ='files/file1.csv')
df1 = load_data(path ='files/file2.csv')

def lower_case_column(df2):
    df2.columns = [i.lower() for i in df2]
    return df2

df2 = pd.concat([df,df1], ignore_index='TRUE')\
.pipe(lower_case_column)
#.pipe(rename_columns)

df2.head(3)

customer          st gender education customer lifetime value   income  \
0  RB50392  Washington    NaN    Master                     NaN      0.0   
1  QZ44356     Arizona      F  Bachelor              697953.59%      0.0   
2  AI49188      Nevada      F  Bachelor             1288743.17%  48767.0   

   monthly premium auto number of open complaints    policy type  \
0                1000.0                    1/0/00  Personal Auto   
1                  94.0                    1/0/00  Personal Auto   
2                 108.0                    1/0/00  Personal Auto   

   vehicle class  total claim amount  
0  Four-Door Car            2.704934  
1  Four-Door Car         1131.464935  
2   Two-Door Car          566.472247

## 1. Aggregate data into one Data Frame using Pandas. <a class="anchor" id="1"></a>

In [2]:


df= pd.read_csv('files/file1.csv')
df1=pd.read_csv('files/file2.csv')



In [3]:
#df

In [4]:
set(df.columns) == set(df1.columns)

True

In [5]:
#concat or append can be used to combine both files
#ignore_index='TRUE' is important, otherwhise the previous index will be used

df2=pd.concat([df,df1], ignore_index='TRUE')

In [6]:
#df2

## 2. Standardizing header names <a class="anchor" id="2"></a>



In [7]:
df2.columns = [i.lower() for i in df2.columns]
df2.columns

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

## 3. Deleting and rearranging columns 
delete the column customer as it is only a unique identifier for each row of data <a class="anchor" id="3"></a>

In [8]:
#delete column 'customer'
#df2 = df2.drop(columns = 'customer')

In [9]:
#df2

## 4. Working with data types
Check the data types of all the columns and fix the incorrect ones (for ex. customer lifetime value and number of complaints ) <a class="anchor" id="4"></a>


In [10]:
#Checking the data types of every column
df2.dtypes

customer                      object
st                            object
gender                        object
education                     object
customer lifetime value       object
income                       float64
monthly premium auto         float64
number of open complaints     object
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5004 entries, 0 to 5003
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   customer                   2067 non-null   object 
 1   st                         2067 non-null   object 
 2   gender                     1945 non-null   object 
 3   education                  2067 non-null   object 
 4   customer lifetime value    2060 non-null   object 
 5   income                     2067 non-null   float64
 6   monthly premium auto       2067 non-null   float64
 7   number of open complaints  2067 non-null   object 
 8   policy type                2067 non-null   object 
 9   vehicle class              2067 non-null   object 
 10  total claim amount         2067 non-null   float64
dtypes: float64(3), object(8)
memory usage: 430.2+ KB


In [12]:
#customer lifetime value should be a float and not a %

def function(x):
    x= str(x)

    if x != "nan":
        #all vales besides of the last % shall be a float number
        y = x [:-1]
        return float (y)
    else:
        return 0

df2["customer lifetime value"] = df2["customer lifetime value"].apply(function)




In [13]:
# values of 'number of complaints'
df2["number of open complaints"].value_counts()



1/0/00    1626
1/1/00     247
1/2/00      93
1/3/00      60
1/4/00      29
1/5/00      12
Name: number of open complaints, dtype: int64

In [14]:
#number of complaints should only disply the 3rd character
def function2(x):
    x= str(x)

    if x != "nan":
        #all vales besides of the last % shall be a float number
        y = x[2]
        return int(y)
    else:
        return 0

df2["number of open complaints"] = df2["number of open complaints"].apply(function2)




In [15]:
#check of the function
df2["number of open complaints"].unique()



array([0, 2, 1, 3, 5, 4])

## 5. Filtering data and Correcting typos 
Filter the data in state and gender column to standardize the texts in those columns <a class="anchor" id="5"></a>


In [16]:
#analyse the uniques in st
df2.st.unique()


array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [17]:
#cleaning the state names
def st_clean(x):
    if not x == x:
    #then i know that x is = none
        return x
    else:
        states= {'Arizona' : 'AZ', 
                 'California': 'CA',
                 'Nevada' : 'NV', 
                 'Cali' :'CA,', 
                 'Oregon':'OR', 
                 'AZ' :'AZ', 
                 'WA':'WA',
                 'Washington':'WA',
                 'Cali':'CA'}
        
        return states[x]

In [18]:
#apply the function to the main df2
df2["st"] = df2["st"].apply(st_clean)

In [19]:
#analyse the uniques in gender
df2.gender.unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [20]:
#cleaning the gender names
def gender1_clean(x):
    if not x == x:
    #then i know that x is = none
        return x
    else:
        g = {'F': 'F', 
                 'M' : 'M', 
                 'Femal': 'F',
                 'Male' : 'M', 
                 'female' :'F'}
        
        return g[x]
        





In [21]:
df2["gender"] = df2["gender"].apply(gender1_clean)

In [22]:
df2.gender.unique()

array([nan, 'F', 'M'], dtype=object)

## 6. Removing duplicates <a class="anchor" id="6"></a>


In [23]:
df2.drop_duplicates()

customer  st gender             education  customer lifetime value  \
0     RB50392  WA    NaN                Master                     0.00   
1     QZ44356  AZ      F              Bachelor                697953.59   
2     AI49188  NV      F              Bachelor               1288743.17   
3     WW63253  CA      M              Bachelor                764586.18   
4     GA49547  WA      M  High School or Below                536307.65   
...       ...  ..    ...                   ...                      ...   
4999  HV85198  AZ      M                Master                847141.75   
5000  BS91566  AZ      F               College                543121.91   
5001  IL40123  NV      F               College                568964.41   
5002  MY32149  CA      F                Master                368672.38   
5003  SA91515  CA      M              Bachelor                399258.39   

       income  monthly premium auto  number of open complaints  \
0         0.0                1000.0                          0   
1         0.0                  94.0                          0   
2     48767.0                 108.0                          0   
3         0.0                 106.0                          0   
4     36357.0                  68.0                          0   
...       ...                   ...                        ...   
4999  63513.0                  70.0                          0   
5000  58161.0                  68.0                          0   
5001  83640.0                  70.0                          0   
5002      0.0                  96.0                          0   
5003      0.0                 111.0                          0   

         policy type  vehicle class  total claim amount  
0      Personal Auto  Four-Door Car            2.704934  
1      Personal Auto  Four-Door Car         1131.464935  
2      Personal Auto   Two-Door Car          566.472247  
3     Corporate Auto            SUV          529.881344  
4      Personal Auto  Four-Door Car           17.269323  
...              ...            ...                 ...  
4999   Personal Auto  Four-Door Car          185.667213  
5000  Corporate Auto  Four-Door Car          140.747286  
5001  Corporate Auto   Two-Door Car          471.050488  
5002   Personal Auto   Two-Door Car           28.460568  
5003   Personal Auto            SUV          700.349052  

[2065 rows x 11 columns]

In [24]:
#index should be from 0 to 2055
import numpy as np
df2.index = np.arange(0,5004)

In [25]:
#df2

## 7. Optional:Replacing null values 
Replace missing values with means of the column (for numerical columns) <a class="anchor" id="7"></a>

In [26]:
df2.columns

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

In [27]:
df2["customer lifetime value"].mean()

321081.0141846531

In [28]:
#replace empty fields with mean
df2['customer lifetime value'].fillna(df2["customer lifetime value"].mean(),inplace=True )

In [29]:
df2['income'].fillna(df2["income"].mean(),inplace=True)

In [30]:
df2['monthly premium auto'].fillna(df2["monthly premium auto"].mean(),inplace=True)

In [31]:
df2['total claim amount'].fillna(df2["total claim amount"].mean(),inplace=True)

In [32]:
df2['number of open complaints'].fillna(df2["number of open complaints"].mean(),inplace=True)

In [33]:
# isn't working:
#df2 = df2.applymap(lambda i: i.mean() if type(df2.columns) == float or  type(df2.columns)== int else i)

In [34]:
df2.isnull().sum().sum()

17744

## 8. Bucketing the data 
Write a function to replace column "State" to different zones. California as West Region, Oregon as North West, and Washington as East, and Arizona and Nevada as Central <a class="anchor" id="8"></a>


In [35]:
df2.st.unique()
def st_region(x):
    if not x == x:
    #then i know that x is = none
        return x
    else:
        region= {'AZ': 'Central', 
                  'CA': 'West',
                 'NV': 'Central', 
                 'OR':'North West', 
                  'AZ':'Central', 
                 'WA':'East'}
        
        return region[x]
    
df2["st"] = df2["st"].apply(st_region)

In [36]:
df2 = df2.rename(columns={'st': 'region'})

## 9. Standardizing the data 
Use string functions to standardize the text data (lower case) <a class="anchor" id="9"></a>

In [37]:
df2 = df2.applymap(lambda i: i.lower() if type(i) == str else i)


In [38]:
# of topic lambda
def my_func(x):
    return x **2
#is like lambda but lambda cannot be called later (have no specific name), useful if you just need a function ones:
'lambda x : x **2'

'lambda x : x **2'


## 10. Which columns are numerical? <a class="anchor" id="10"></a>

In [39]:
df2_numerical= df2.select_dtypes(include=np.number).columns.tolist()
df2_numerical

['customer lifetime value',
 'income',
 'monthly premium auto',
 'number of open complaints',
 'total claim amount']

## 11. Which columns are categorical? <a class="anchor" id="11"></a>

In [40]:
df2_categorical = df2.select_dtypes(include=object).columns.tolist()
df2_categorical

['customer', 'region', 'gender', 'education', 'policy type', 'vehicle class']